# Generated by Django 3.0.7 on 2020-10-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201006_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likenumber',
        ),
    ]
